### ISSUE TITLE
Printer Defaults not set with Add / Modify command

### ISSUE THREAD

**Issue by bwussler** [michaelrsweet/lprint#75] opened 2022-08-23 19:49 UTC
Hi, I'm having issues changing settings on a printer. I tried including options when adding a new printer but did not have any luck. I have no issues changing them through the web interface, but only have issues in command line. 

I've tried these.
`lprint modify -d TestPrinter01 -o printer-darkness=65`
`lprint add -d TestPrinter01 -m zpl_4inch-600dpi-tt -v socket://192.168.0.100 -o printer-darkness=65`

The command does not error out, but also doesn't change the default settings. I've had a good experience with the project so far, so I just wanted to mention that everything you're doing is awesome. There is a good chance I'm doing something wrong. The command works for changing media-ready without issues. 

Thanks.

**Comment by michaelrsweet** [comment] 2022-11-11 19:01
Confirmed, and print-darkness-default is coming through in the Set-Printer-Attributes request. Maybe something in PAPPL is going wrong...

**Comment by michaelrsweet** [comment] 2024-01-18 19:46
This seems to be fixed in current PAPPL/LPrint.

**Closed by michaelrsweet** 2024-01-18 19:46 UTC
Labels: bug, priority-high
