### ISSUE TITLE
lprint (1.1) not working on ubuntu 24.04 [Xprinter XP-460B]

### ISSUE THREAD

**Issue by gregoiregentil** [michaelrsweet/lprint#138] opened 2024-04-27 21:13 UTC
I have a Xprinter XP-460B. I was running Ubuntu 20.04 which had lprint 1.0. I had a .lprintrc file setup just fine. Everything was working over USB.

I have updated my PC to Ubuntu 24.04. The default is lprint 1.1: https://packages.ubuntu.com/noble/lprint

I can run:

`lprint devices`

and:

`lprint add -v usb://Xprinter/Xprinter/XP-460B?serial=S... -d xprinter-xp-460b -m zpl_4inch-203dpi-dt`

But when I print a label, nothing happens. I see that there is a /etc/lprint.conf file now. The content looks OK and similar to my fine tuned ~/.lprintrc. A job is added to the last line of this conf file with status 5.

I have downgraded the deb package to 1.0 and everything works fine with ~/.lprintrc

I'm OK to continue my life with Ubuntu 24.04 + lprint 1.0 and I'm also willing to debug the problem to make work lprint 1.1.

**Comment by gregoiregentil** [comment] 2024-04-29 22:36
I made some progress. Yes, the usb: URI was not correct. I inadvertently added a MAKE. So now, I manage to print something but the image is scaled down compared to version 1.0.

In version 1.0, I had:

```
media-col-default 0,0,0,0,0,oe_4x6-label_4x6in,main-roll,0,0,2,labels
media-col-ready-0 0,0,0,0,0,oe_4x6-label_4x6in,main-roll,0,0,2,labels
printer-darkness-configured 50
copies-default 1
orientation-requested-default portrait
print-color-mode-default bi-level
print-content-optimize-default auto
print-quality-default normal
```

In version 1.1, I have:
```
DNSSDName xprinter-xp-460b
Contact
MaxActiveJobs 0
MaxCompletedJobs 100
NextJobId 1
ImpressionsCompleted 0
label-mode-configured 
media-col-default bottom="1" left="1" length="15240" name="na_index-4x6_4x6in" right="1" source="main-roll" top="1" tracking="mark" type="labels" width="10160"
media-col-ready0 bottom="1" left="1" length="15240" name="na_index-4x6_4x6in" right="1" source="main-roll" top="1" tracking="mark" type="labels" width="10160"
orientation-requested-default none
print-color-mode-default monochrome
print-content-optimize-default auto
print-quality-default normal
print-scaling-default auto
printer-darkness-configured 50
sides-default one-sided
printer-resolution-default 203x203dpi
```

![a](https://github.com/michaelrsweet/lprint/assets/486156/bd783144-4505-418a-a7c1-02de499d11e6)

Here is a scan of two labels, on left version 1.0, on right version 1.1. What is wrong in my 1.1 configuration? My printout is a 800-x12-0 png image. Is this a problem with print-scaling-default?

**Comment by gregoiregentil** [comment] 2024-05-04 16:58
Any idea on my problem?

**Comment by michaelrsweet** [comment] 2024-05-04 21:06
You could try using print-scaling=fit; it is possible the resolution information in the PNG file is bogus which will lead to bad scaling.

**Comment by michaelrsweet** [comment] 2024-05-17 14:13
Closing for now; if you have more info we can continue trying to determine the cause of your problems.

**Closed by michaelrsweet** 2024-05-17 14:13 UTC
Labels: unable-to-reproduce, investigating

**Comment by gregoiregentil** [comment] 2024-05-17 19:11
Thank you for your help. I'm fine with the "unable-to-reproduce". For the records, unfortunately, the issue is not fixed for me. I tried all options possible for "print-scaling-default". Either it was the problem or the printer didn't want to print. I'm fine to keep lprint 1.0 on my computer which works very  well.
